import Link from "next/link";

import { LegalPageLayout } from "@/components/legal/LegalPageLayout";
import { ENTITY_NAME, SUPPORT_EMAIL } from "@/lib/legalContent";

export const metadata = { title: "Disclaimer — Riviso" };

export default function DisclaimerPage() {
  return (
    <LegalPageLayout
      title="Disclaimer"
      summary={
        <span>
          Riviso generates a starting draft using AI — always review before publishing. We don&apos;t guarantee
          rankings, traffic, or indexing outcomes, and we&apos;re not responsible for third-party platforms you
          connect.
        </span>
      }
    >
      <h2>1. AI-generated content</h2>
      <p>
        Riviso uses artificial intelligence (via OpenAI) to generate article text, metadata, and images based on
        the prompts, keywords, and settings you provide. AI-generated content may contain factual inaccuracies,
        outdated information, unintentional bias, or content that resembles existing works. It is provided as a
        drafting aid, not as verified, professional, or legal advice. You are solely responsible for reviewing,
        fact-checking, and editing any AI-generated content before publishing it, and for ensuring it complies with
        applicable law (including copyright, defamation, and advertising standards) in your jurisdiction.
      </p>

      <h2>2. No professional advice</h2>
      <p>Nothing generated by or displayed within Riviso constitutes legal, financial, medical, or other professional advice. Content on SEO, marketing, or business topics generated using the Service is for general informational purposes only.</p>

      <h2>3. No guaranteed results</h2>
      <p>
        We do not guarantee any specific outcome from using Riviso, including but not limited to search engine
        rankings, indexing, organic traffic, conversions, or revenue. Search engine and platform algorithms change
        frequently and are outside our control. Automated actions such as Google Search Console indexing requests
        are best-effort, depend on Google&apos;s own systems and policies, and may not result in indexing or ranking
        changes.
      </p>

      <h2>4. Third-party platforms and links</h2>
      <p>
        Riviso integrates with third-party platforms (WordPress, Shopify, Google) that you choose to connect. We
        are not responsible for the availability, security, content, or policies of those third-party platforms,
        or for any changes they make to their APIs or terms that affect the Service. Content you generate may also
        link to or reference third-party websites; we do not endorse and are not responsible for third-party
        content.
      </p>

      <h2>5. &ldquo;As is&rdquo; service</h2>
      <p>The Service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without warranties of any kind, to the fullest extent permitted by applicable law. See our <Link href="/terms">Terms & Conditions</Link> for the full limitation of liability.</p>

      <h2>6. Your responsibility</h2>
      <p>By publishing content generated with Riviso, you accept responsibility for that content as if you had written it yourself, including compliance with applicable advertising, consumer protection, and content laws in the jurisdictions where it is published or viewed.</p>

      <h2>7. Contact</h2>
      <p>Questions about this disclaimer: <strong>{SUPPORT_EMAIL}</strong>, operated by {ENTITY_NAME}.</p>
    </LegalPageLayout>
  );
}
